name: 'PR Lint GitHub Action'
description: 'PR Lint for GitHub Actions'
author: 'Farhad Safarov'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  title-regex:
    description: 'Title regex to match'
    required: true
    default: '^\[PROJECT-\d*\]\ '
  github-token:
    description: 'Title regex to match'
    required: true
  atlassian-token:
    description: 'Title regex to match'
    required: true
branding:
  icon: 'edit-3'
  color: 'blue'
